apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: splunk-forwarder-operator
  annotations:
    name: annotation
spec:
  scopes:
  - Cluster
  phases:
  - name: crds
  - name: namespace
  - name: rbac
  - name: deploy
  - name: cleanup-rbac
  - name: cleanup-deploy
  availabilityProbes:
  - probes:
    - condition:
        type: Available
        status: 'True'
    - fieldsEqual:
        fieldA: .status.updatedReplicas
        fieldB: .status.replicas
    selector:
      kind:
        group: apps
        kind: Deployment
  config:
    openAPIV3Schema:
      properties:
        image:
          description: Operator image to deploy
          type: string
        namespace:
          description: Namespace to deploy the operator into
          type: string
      required:
      - image
      - namespace
      type: object
test:
  template:
  - name: default
    context:
      package:
        metadata:
          name: splunk-forwarder-operator
          namespace: openshift-splunk-forwarder-operator
      config:
        image: quay.io/app-sre/splunk-forwarder-operator:test
        namespace: openshift-splunk-forwarder-operator
