apiVersion: v1
kind: Template
metadata:
  name: olm-artifacts-template

parameters:
- name: REGISTRY_IMG
  required: true
- name: CHANNEL
  value: staging
- name: IMAGE_TAG
  value: latest

objects:
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    name: splunk-forwarder-operator-sss
    namespace: splunk-forwarder-operator
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: "true"
    resourceApplyMode: Sync
    resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: openshift-splunk-forwarder-operator
        annotations:
          openshift.io/node-selector: ''
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: openshift-security
        annotations:
          openshift.io/node-selector: ''
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        creationTimestamp: null
        name: openshift-splunk-forwarder-operator
      rules:
      - apiGroups:
        - ""
        resources:
        - pods
        - services
        - endpoints
        - persistentvolumeclaims
        - events
        - configmaps
        - secrets
        verbs:
        - '*'
      - apiGroups:
        - apps
        resources:
        - deployments
        - daemonsets
        - replicasets
        - statefulsets
        verbs:
        - '*'
      - apiGroups:
        - monitoring.coreos.com
        resources:
        - servicemonitors
        verbs:
        - get
        - create
      - apiGroups:
        - apps
        resourceNames:
        - splunk-forwarder-operator
        resources:
        - deployments/finalizers
        verbs:
        - update
      - apiGroups:
        - splunkforwarder.managed.openshift.io
        resources:
        - '*'
        verbs:
        - '*'

    - apiVersion: security.openshift.io/v1
      metadata:
        name: splunkforwarder
      allowHostDirVolumePlugin: true
      allowHostIPC: false
      allowHostNetwork: false
      allowHostPID: false
      allowHostPorts: false
      allowPrivilegeEscalation: true
      allowPrivilegedContainer: true
      allowedCapabilities:
      - '*'
      allowedUnsafeSysctls:
      - '*'
      defaultAddCapabilities: null
      fsGroup:
        type: RunAsAny
      kind: SecurityContextConstraints
      priority: null
      readOnlyRootFilesystem: false
      requiredDropCapabilities: null
      runAsUser:
        type: RunAsAny
      seLinuxContext:
        type: RunAsAny
      seccompProfiles:
      - '*'
      supplementalGroups:
        type: RunAsAny
      users:
      - system:serviceaccount:openshift-security:default
      volumes:
      - '*'
    - kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: splunk-forwarder-operator
      subjects:
      - kind: ServiceAccount
        name: default
        namespace: openshift-splunk-forwarder-operator
      roleRef:
        kind: ClusterRole
        name: openshift-splunk-forwarder-operator
        apiGroup: rbac.authorization.k8s.io
    - apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      metadata:
        name: splunk-forwarder-operator-catalog
        namespace: openshift-splunk-forwarder-operator
      spec:
        sourceType: grpc
        image: ${REGISTRY_IMG}:${CHANNEL}-${IMAGE_TAG}
        displayName: splunk-forwarder-operator Registry
        publisher: SRE
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: node-role.kubernetes.io/infra
                  operator: Exists
              weight: 1
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/infra
            operator: Exists

    - apiVersion: operators.coreos.com/v1alpha2
      kind: OperatorGroup
      metadata:
        name: splunk-forwarder-operator-og
        namespace: openshift-splunk-forwarder-operator
      spec:
        targetNamespaces:
        - openshift-splunk-forwarder-operator

    - apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: openshift-splunk-forwarder-operator
        namespace: openshift-splunk-forwarder-operator
      spec:
        channel: ${CHANNEL}
        name: splunk-forwarder-operator
        source: splunk-forwarder-operator-catalog
        sourceNamespace: openshift-splunk-forwarder-operator

    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        creationTimestamp: null
        name: splunk-forwarder-operator
      rules:
      - apiGroups:
        - ""
        resources:
        - secrets
        verbs:
        - list
        - get
      - apiGroups:
        - ""
        resources:
        - configmaps
        verbs:
        - list
        - get
        - update
        - create
        - delete
      - apiGroups:
        - apps
        resources:
        - daemonsets
        verbs:
        - get
        - create
        - list
        - update
        - delete
      - apiGroups:
        - splunkforwarders.splunkforwarder.managed.openshift.io
        resources:
        - '*'
        verbs:
        - '*'
      - apiGroups:
        - config.openshift.io
        resources:
        - infrastructures
        verbs:
        - get
        - list
        - watch

    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: splunk-forwarder-operator
        namespace: openshift-splunk-forwarder-operator


    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: splunk-forwarder-operator-clusterrolebinding
      subjects:
      - kind: ServiceAccount
        name: splunk-forwarder-operator
        namespace: openshift-splunk-forwarder-operator
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: splunk-forwarder-operator

    secretReferences:
    - source:
        name: splunk-auth
        namespace: splunk-forwarder-operator
      target:
        name: splunk-auth
        namespace: openshift-security

- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    name: splunk-forwarder-operator-cr-sss
    namespace: splunk-forwarder-operator
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: "true"
        api.openshift.com/environment: production
      matchExpressions:
        - { key: api.openshift.com/noalerts, operator: NotIn, values: ["true"] }
        - { key: hive.openshift.io/cluster-region, operator: NotIn, values: ["cn-north-1", "cn-northwest-1"] }
    resourceApplyMode: Sync
    resources:
    - apiVersion: splunkforwarder.managed.openshift.io/v1alpha1
      kind: SplunkForwarder
      metadata:
        name: splunkforwarder
        namespace: openshift-security
      spec:
        image: quay.io/app-sre/splunk-forwarder
        imageTag: 8.0.3-a6754d8441bf
        heavyForwarderImage: quay.io/app-sre/splunk-heavyforwarder
        heavyForwarderSelector: infra
        useHeavyForwarder: true
        splunkLicenseAccepted: true
        filters:
        - name: ignore_serviceaccount_users
          filter: '"user":{"username":"(?:system:serviceaccount:[^"]+)".*"userAgent":"(?:(?![^"]*(Mozilla|oc|Wget|curl|kubectl(?:\.exe)?)/)[^"]+)'
        - name: ignore_system_node_users
          filter: '"user":{"username":"system:node:[^"]+"'
        - name: ignore_chatty_system_users
          filter: '"user":{"username":"system:(?:kube-(?:controller-manager|scheduler|apiserver-cert-syncer)|apiserver|aggregator)"'
        splunkInputs:
        - path: /host/var/log/openshift-apiserver/audit.log
          index: openshift_managed_audit
          whiteList: \.log$
          sourceType: _json
        - path: /host/var/log/kube-apiserver/audit.log
          index: openshift_managed_audit
          whiteList: \.log$
          sourceType: _json
        - path: /host/var/log/pods/*_ip-*-*-*-*ec2internal-debug_*/container-*/*.log
          index: openshift_managed_debug_node
          whiteList: \.log$
          sourceType: openshift:debug
        - path: /host/var/log/openshift_managed_pod_creation.log
          index: openshift_managed_pod_creation
          whiteList: \.log$
          sourceType: _json
        - path: /host/var/log/openshift_managed_malware_scan.log
          index: openshift_managed_malware_scan
          whiteList: \.log$
          sourceType: _json

- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    name: splunk-forwarder-operator-cr-stg-sss
    namespace: splunk-forwarder-operator
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: "true"
        api.openshift.com/environment: staging
      matchExpressions:
        - { key: api.openshift.com/noalerts, operator: NotIn, values: ["true"] }
        - { key: hive.openshift.io/cluster-region, operator: NotIn, values: ["cn-north-1", "cn-northwest-1"] }
    resourceApplyMode: Sync
    resources:
    - apiVersion: splunkforwarder.managed.openshift.io/v1alpha1
      kind: SplunkForwarder
      metadata:
        name: splunkforwarder
        namespace: openshift-security
      spec:
        image: quay.io/app-sre/splunk-forwarder
        imageTag: 8.0.3-a6754d8441bf
        heavyForwarderImage: quay.io/app-sre/splunk-heavyforwarder
        heavyForwarderSelector: infra
        useHeavyForwarder: true
        splunkLicenseAccepted: true
        splunkInputs:
        - path: /host/var/log/pods/*_ip-*-*-*-*ec2internal-debug_*/container-*/*.log
          index: openshift_managed_debug_node
          whiteList: \.log$
          sourceType: openshift:debug
