apiVersion: v1
kind: Template
metadata:
  name: olm-artifacts-template

parameters:
- name: REGISTRY_IMG
  required: true
- name: CHANNEL
  value: staging
- name: IMAGE_TAG
  value: latest
- name: REPO_DIGEST
  required: true
- name: ALERTS_SKIP_LEGALENTITY_IDS
  value: '["none"]'
- name: OPERATOR_NAME
  value: splunk-forwarder-operator
  required: true

objects:
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    annotations:
      component-display-name: Splunk Forwarder Operator
      component-name: ${OPERATOR_NAME}
      telemeter-query: csv_succeeded{_id="$CLUSTER_ID",name=~"${OPERATOR_NAME}.*",exported_namespace=~"openshift-.*",namespace="openshift-operator-lifecycle-manager"} == 1
    name: splunk-forwarder-operator-sss
    namespace: splunk-forwarder-operator
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: "true"
    resourceApplyMode: Sync
    resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: openshift-splunk-forwarder-operator
        annotations:
          openshift.io/node-selector: ''
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: openshift-security
        annotations:
          openshift.io/node-selector: ''
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        creationTimestamp: null
        name: openshift-splunk-forwarder-operator
      rules:
      - apiGroups:
        - ""
        resources:
        - pods
        - services
        - endpoints
        - persistentvolumeclaims
        - events
        - configmaps
        - secrets
        verbs:
        - '*'
      - apiGroups:
        - apps
        resources:
        - deployments
        - daemonsets
        - replicasets
        - statefulsets
        verbs:
        - '*'
      - apiGroups:
        - monitoring.coreos.com
        resources:
        - servicemonitors
        verbs:
        - get
        - create
      - apiGroups:
        - apps
        resourceNames:
        - splunk-forwarder-operator
        resources:
        - deployments/finalizers
        verbs:
        - update
      - apiGroups:
        - splunkforwarder.managed.openshift.io
        resources:
        - '*'
        verbs:
        - '*'

    - apiVersion: security.openshift.io/v1
      metadata:
        name: splunkforwarder
      allowHostDirVolumePlugin: true
      allowHostIPC: false
      allowHostNetwork: false
      allowHostPID: false
      allowHostPorts: false
      allowPrivilegeEscalation: true
      allowPrivilegedContainer: true
      allowedCapabilities:
      - '*'
      allowedUnsafeSysctls:
      - '*'
      defaultAddCapabilities: null
      fsGroup:
        type: RunAsAny
      kind: SecurityContextConstraints
      priority: null
      readOnlyRootFilesystem: false
      requiredDropCapabilities: null
      runAsUser:
        type: RunAsAny
      seLinuxContext:
        type: RunAsAny
      seccompProfiles:
      - '*'
      supplementalGroups:
        type: RunAsAny
      users:
      - system:serviceaccount:openshift-security:default
      volumes:
      - '*'
    - kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: splunk-forwarder-operator
      subjects:
      - kind: ServiceAccount
        name: default
        namespace: openshift-splunk-forwarder-operator
      roleRef:
        kind: ClusterRole
        name: openshift-splunk-forwarder-operator
        apiGroup: rbac.authorization.k8s.io
    - apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      metadata:
        name: splunk-forwarder-operator-catalog
        namespace: openshift-splunk-forwarder-operator
      spec:
        sourceType: grpc
        image: ${REPO_DIGEST}
        displayName: splunk-forwarder-operator Registry
        publisher: SRE
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: node-role.kubernetes.io/infra
                  operator: Exists
              weight: 1
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/infra
            operator: Exists

    - apiVersion: operators.coreos.com/v1alpha2
      kind: OperatorGroup
      metadata:
        name: splunk-forwarder-operator-og
        namespace: openshift-splunk-forwarder-operator
      spec:
        targetNamespaces:
        - openshift-splunk-forwarder-operator

    - apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: openshift-splunk-forwarder-operator
        namespace: openshift-splunk-forwarder-operator
      spec:
        channel: ${CHANNEL}
        name: splunk-forwarder-operator
        source: splunk-forwarder-operator-catalog
        sourceNamespace: openshift-splunk-forwarder-operator

    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        creationTimestamp: null
        name: splunk-forwarder-operator
      rules:
      - apiGroups:
        - ""
        resources:
        - secrets
        verbs:
        - list
        - get
      - apiGroups:
        - ""
        resources:
        - configmaps
        verbs:
        - list
        - get
        - update
        - create
        - delete
      - apiGroups:
        - apps
        resources:
        - daemonsets
        verbs:
        - get
        - create
        - list
        - update
        - delete
      - apiGroups:
        - splunkforwarders.splunkforwarder.managed.openshift.io
        resources:
        - '*'
        verbs:
        - '*'
      - apiGroups:
        - config.openshift.io
        resources:
        - infrastructures
        verbs:
        - get
        - list
        - watch

    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: splunk-forwarder-operator
        namespace: openshift-splunk-forwarder-operator


    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: splunk-forwarder-operator-clusterrolebinding
      subjects:
      - kind: ServiceAccount
        name: splunk-forwarder-operator
        namespace: openshift-splunk-forwarder-operator
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: splunk-forwarder-operator


- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    name: splunk-forwarder-operator-osd-splunk-auth
    namespace: splunk-forwarder-operator
  spec:
    clusterDeploymentSelector:
      matchExpressions:
      - { key: api.openshift.com/managed, operator: In, values: ["true"] }
      - { key: api.openshift.com/environment, operator: In, values: ["production", "staging"] }
      - { key: api.openshift.com/noalerts, operator: NotIn, values: ["true"] }
      - { key: ext-managed.openshift.io/noalerts, operator: NotIn, values: ["true"] }
      - key: api.openshift.com/legal-entity-id
        operator: NotIn
        values: ${{ALERTS_SKIP_LEGALENTITY_IDS}}
      - { key: hive.openshift.io/cluster-region, operator: NotIn, values: ["cn-north-1", "cn-northwest-1"] }
      - { key: api.openshift.com/fedramp, operator: DoesNotExist }
    secretMappings:
    - sourceRef:
        name: splunk-auth
        namespace: splunk-forwarder-operator
      targetRef:
        name: splunk-auth
        namespace: openshift-security

- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    name: splunk-forwarder-operator-cr-sss
    namespace: splunk-forwarder-operator
  spec:
    clusterDeploymentSelector:
      matchExpressions:
        - { key: api.openshift.com/managed, operator: In, values: ["true"] }
        - { key: api.openshift.com/environment, operator: In, values: ["production"] }
        - { key: api.openshift.com/noalerts, operator: NotIn, values: ["true"] }
        - { key: ext-managed.openshift.io/noalerts, operator: NotIn, values: ["true"] }
        - key: api.openshift.com/legal-entity-id
          operator: NotIn
          values: ${{ALERTS_SKIP_LEGALENTITY_IDS}}
        - { key: hive.openshift.io/cluster-region, operator: NotIn, values: ["cn-north-1", "cn-northwest-1"] }
        - { key: api.openshift.com/fedramp, operator: DoesNotExist }
    resourceApplyMode: Sync
    resources:
    - apiVersion: splunkforwarder.managed.openshift.io/v1alpha1
      kind: SplunkForwarder
      metadata:
        name: splunkforwarder
        namespace: openshift-security
      spec:
        image: quay.io/app-sre/splunk-forwarder
        imageDigest: sha256:f4aadcdd52400bee07587d81c8000ff99af18c78d1b0c57d3cb7fe41e3393a66
        heavyForwarderImage: quay.io/app-sre/splunk-heavyforwarder
        heavyForwarderDigest: sha256:714780cf50e80251662538aaa4a55ba1a6e6c5aaca7f09d160f628fcbd7a54d8
        useHeavyForwarder: false
        splunkLicenseAccepted: true
        filters:
        - name: ignore_serviceaccount_users
          filter: '"user":{"username":"(?:system:serviceaccount:(?!openshift-backplane-)[^"]+)'
        - name: ignore_system_node_users
          filter: '"user":{"username":"system:node:[^"]+"'
        - name: ignore_chatty_system_users
          filter: '"user":{"username":"system:(?:kube-(?:controller-manager|scheduler|apiserver-cert-syncer)|apiserver|aggregator)"'
        - name: ignore_well_known_oauth_endpoint
          filter: '"requestURI":"/.well-known/oauth-authorization-server"'
        - name: ignore_livez_health_check
          filter: '"requestURI":"/livez"'
        splunkInputs:
        - path: /host/var/log/osd-audit/audit.log
          index: openshift_managed_audit
          whiteList: \.log$
          sourceType: _json
        - path: /host/var/log/pods/*_ip-*-*-*-*ec2internal-debug_*/container-*/*.log
          index: openshift_managed_debug_node
          whiteList: \.log$
          sourceType: openshift:debug
        - path: /host/var/log/openshift_managed_pod_creation.log
          index: openshift_managed_pod_creation
          whiteList: \.log$
          sourceType: _json
        - path: /host/var/log/openshift_managed_malware_scan.log
          index: openshift_managed_malware_scan
          whiteList: \.log$
          sourceType: _json
        - path: /host/var/lib/kubelet/pods/*/volumes/kubernetes.io~*/pvc-*/backplane-audit.log
          index: openshift_managed_backplane_prod
          sourceType: _json
          whiteList: \.log$

- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    name: splunk-forwarder-operator-cr-fr-sss
    namespace: splunk-forwarder-operator
  spec:
    clusterDeploymentSelector:
      matchExpressions:
        - { key: api.openshift.com/managed, operator: In, values: ["true"] }
        - { key: api.openshift.com/environment, operator: In, values: ["production"] }
        - { key: api.openshift.com/noalerts, operator: NotIn, values: ["true"] }
        - { key: ext-managed.openshift.io/noalerts, operator: NotIn, values: ["true"] }
        - { key: api.openshift.com/fedramp, operator: In, values: ["true"] }
    resourceApplyMode: Sync
    resources:
    - apiVersion: splunkforwarder.managed.openshift.io/v1alpha1
      kind: SplunkForwarder
      metadata:
        name: splunkforwarder
        namespace: openshift-security
      spec:
        image: quay.io/app-sre/splunk-forwarder
        imageDigest: sha256:f4aadcdd52400bee07587d81c8000ff99af18c78d1b0c57d3cb7fe41e3393a66
        heavyForwarderImage: quay.io/app-sre/splunk-heavyforwarder
        heavyForwarderDigest: sha256:714780cf50e80251662538aaa4a55ba1a6e6c5aaca7f09d160f628fcbd7a54d8
        useHeavyForwarder: false
        splunkLicenseAccepted: true
        splunkInputs:
        - index: rh_osd_cluster_audit
          path: /host/var/log/osd-audit/audit.log
          sourceType: _json
          whiteList: \.log$
        - index: rh_osd_pod_creation
          path: /host/var/log/openshift_managed_pod_creation.log
          sourceType: _json
          whiteList: \.log$
        - index: rh_osd_malware_scan
          path: /host/var/log/openshift_managed_malware_scan.log
          sourceType: _json
          whiteList: \.log$
        - index: rh_osd_debug_node
          path: /host/var/log/pods/default_ip-*-debug_*/container-*/*.log
          sourceType: openshift:debug
          whiteList: \.log$

- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    name: splunk-forwarder-operator-cr-stg-sss
    namespace: splunk-forwarder-operator
  spec:
    clusterDeploymentSelector:
      matchExpressions:
        - { key: api.openshift.com/managed, operator: In, values: ["true"] }
        - { key: api.openshift.com/environment, operator: In, values: ["staging"] }
        - { key: api.openshift.com/noalerts, operator: NotIn, values: ["true"] }
        - { key: ext-managed.openshift.io/noalerts, operator: NotIn, values: ["true"] }
        - { key: hive.openshift.io/cluster-region, operator: NotIn, values: ["cn-north-1", "cn-northwest-1"] }
        - { key: api.openshift.com/fedramp, operator: DoesNotExist }
    resourceApplyMode: Sync
    resources:
    - apiVersion: splunkforwarder.managed.openshift.io/v1alpha1
      kind: SplunkForwarder
      metadata:
        name: splunkforwarder
        namespace: openshift-security
      spec:
        image: quay.io/app-sre/splunk-forwarder
        imageDigest: sha256:f4aadcdd52400bee07587d81c8000ff99af18c78d1b0c57d3cb7fe41e3393a66
        heavyForwarderImage: quay.io/app-sre/splunk-heavyforwarder
        heavyForwarderDigest: sha256:714780cf50e80251662538aaa4a55ba1a6e6c5aaca7f09d160f628fcbd7a54d8
        useHeavyForwarder: false
        splunkLicenseAccepted: true
        splunkInputs:
        - path: /host/var/log/pods/*_ip-*-*-*-*ec2internal-debug_*/container-*/*.log
          index: openshift_managed_debug_node
          whiteList: \.log$
          sourceType: openshift:debug
        - path: /host/var/log/osd-audit/audit.log
          index: openshift_managed_audit_stage
          whiteList: \.log$
          sourceType: _json

- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    name: splunk-forwarder-operator-cr-fr-stg-sss
    namespace: splunk-forwarder-operator
  spec:
    clusterDeploymentSelector:
      matchExpressions:
        - { key: api.openshift.com/managed, operator: In, values: ["true"] }
        - { key: api.openshift.com/environment, operator: In, values: ["staging", "integration"] }
        - { key: api.openshift.com/fedramp, operator: In, values: ["true"] }
    resourceApplyMode: Sync
    resources:
    - apiVersion: splunkforwarder.managed.openshift.io/v1alpha1
      kind: SplunkForwarder
      metadata:
        name: splunkforwarder
        namespace: openshift-security
      spec:
        image: quay.io/app-sre/splunk-forwarder
        imageDigest: sha256:f4aadcdd52400bee07587d81c8000ff99af18c78d1b0c57d3cb7fe41e3393a66
        heavyForwarderImage: quay.io/app-sre/splunk-heavyforwarder
        heavyForwarderDigest: sha256:714780cf50e80251662538aaa4a55ba1a6e6c5aaca7f09d160f628fcbd7a54d8
        useHeavyForwarder: false
        splunkLicenseAccepted: true
        splunkInputs:
        - index: rh_osd_cluster_audit
          path: /host/var/log/osd-audit/audit.log
          sourceType: _json
          whiteList: \.log$
        - index: rh_osd_pod_creation
          path: /host/var/log/openshift_managed_pod_creation.log
          sourceType: _json
          whiteList: \.log$
        - index: rh_osd_malware_scan
          path: /host/var/log/openshift_managed_malware_scan.log
          sourceType: _json
          whiteList: \.log$
        - index: rh_osd_debug_node
          path: /host/var/log/pods/default_ip-*-debug_*/container-*/*.log
          sourceType: openshift:debug
          whiteList: \.log$
