apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: splunk-forwarder-operator
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - get
  - update
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - create
  - list
  - update
  - delete
- apiGroups:
  - splunkforwarders.splunkforwarder.managed.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  verbs:
  - get
  - list
  - watch
